### PR TITLE
module sync update

### PR DESCRIPTION
**Pull request by jlsherrill**
sync with foreman and update of .travis.yaml to
better match foremans

### CODE REVIEW

**Comment by jlsherrill** [comment]
my first time doing this

**Comment by ehelms** [comment]
LGTM - @stbenjam any comments?

**Comment by stbenjam** [comment]
Looks fine to me

**Review by ehelms — APPROVED** [review]

**Comment by jlsherrill** [comment]
Will open up the other module sync PRs

**Pull request merged**
