### PR TITLE
Use older rake on ruby 1.8.7, sync with Foreman

### PR DESCRIPTION
**Pull request by stbenjam**
Syncing with Foreman's

### CODE REVIEW

**Comment by stbenjam** [comment]
We haven't synced with foreman in a while, want to maybe pull in a couple other things and make sure this works first.

**Comment by ehelms** [comment]
+100 thanks for this @stbenjam ! Just let me know when you think its gtg

**Comment by stbenjam** [comment]
It's a PR party :tada: :balloon: :birthday:   Checking them off once tests pass.
- [x] https://github.com/Katello/puppet-candlepin/pull/43
- [x] https://github.com/Katello/puppet-capsule/pull/77
- [x] https://github.com/Katello/puppet-certs/pull/80
- [x] https://github.com/Katello/puppet-common/pull/10
- [x] https://github.com/Katello/puppet-crane/pull/8
- [x] https://github.com/Katello/puppet-elasticsearch/pull/8
- [x] https://github.com/Katello/puppet-gutterball/pull/21
- [x] https://github.com/Katello/puppet-katello/pull/117
- [x] https://github.com/Katello/puppet-katello_devel/pull/66
- [x] https://github.com/Katello/puppet-pulp/pull/134
- [x] https://github.com/Katello/puppet-qpid/pull/35
- [x] https://github.com/Katello/puppet-service_wait/pull/13

**Comment by stbenjam** [comment]
Good to go

**Comment by ehelms** [comment]
ACK for this change

**Comment by ehelms** [comment]
I will start on each of the modules

**Comment by stbenjam** [comment]
Great, thanks. For some reason I don't have commit to this repo, guess it's not assigned to the Puppet team.

**Comment by ehelms** [comment]
Updated that team -- try now

**Comment by stbenjam** [comment]
Nope, still no big green button

**Comment by stbenjam** [comment]
@ehelms Perms are only set to read: https://github.com/orgs/Katello/teams/installer/repositories

**Comment by ehelms** [comment]
Oops, updated

**Comment by stbenjam** [comment]
Thanks!

**Pull request merged**
